# Before creating this deployment create the TLS secrets:
# kubectl create secret tls horizonsecret --key tls.key.pem --cert tls.crt.pem

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: horizon-ingress
  annotations:
    nginx.ingress.kubernetes.io/app-root: /horizon
    nginx.ingress.kubernetes.io/proxy-body-size: 30g
spec:
  tls:
    - hosts:
      - engines.scloud.switch.ch
      # This assumes tls-secret exists and the SSL
      # certificate contains a CN for foo.bar.com
      secretName: horizonsecret
  rules:
    - host: engines.scloud.switch.ch
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: horizon-svc
              port:
                number: 8080

