apiVersion: v1
data:
  .dockerconfigjson: "{{ dockerpullsecret }}"
kind: Secret
metadata:
  name: gitlabswitch
  namespace: "{{ namespace | default('horizontesting123', true) }}"
type: kubernetes.io/dockerconfigjson
