apiVersion: v1
data:
  .secret_key_store: "{{ horizonsessionsecret }}"
kind: Secret
metadata:
  name: horizonsecretkey
  namespace: "{{ namespace | default('horizontesting123', true) }}"
type: Opaque

