apiVersion: v1
kind: Service
metadata:
  name: horizon-svc
  namespace: "{{ namespace | default('horizontesting123', true) }}"
spec:
  ports:
  - name: apache
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: horizon
