apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis-master
    role: service
  name: redis-master
  namespace: "{{ namespace | default('horizontesting123', true) }}"
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
