kind: Secret
apiVersion: v1
metadata:
  name: horizonsecret
  namespace: "{{ namespace | default('horizontesting123', true) }}"
type: kubernetes.io/tls
data:
  tls.crt: "{{ tlscrt }}"
  tls.key: "{{ tlskey }}"

